# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps: 
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Build and push Docker Image
      uses : mr-smithers-excellent/docker-build-push@v5
      with :
        image: raoufallagui216/react-docker
        registry: docker.io
        tags: v1, latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deployment:
    name : Deployment
    runs-on: ubuntu-latest
    steps:
      - name:  testing my server conx ssh
        uses : appleboy/ssh-action@master
        with:
          host: 102.219.179.94
          username: root
          password: @q94M7bI4*v@
          port: 22
          script: cd ../var
